# Generated by Django 3.1.1 on 2020-09-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rollno',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
